<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.youdatax.web</groupId>
  <artifactId>youdatax-web-authn-service-main-configuration</artifactId>
  <version>0.0.3-SNAPSHOT</version>
  <name>yospace-ext-common-auth-configuration</name>
  <description>yospace-ext-common-auth-configuration</description>
  
  <dependencies>
<!--    api(project(":spi:common:auth-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-auth</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
      
<!--    testImplementation(project(":core:common:junit"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>junit</artifactId>
        <version>0.18.0</version>
        <scope>test</scope>
      </dependency>
   </dependencies> 
</project>