<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.youdatax.web</groupId>
  <artifactId>youdatax-web-auth-lib-authz-oauth2</artifactId>
  <version>0.0.3-SNAPSHOT</version>
  <name>yospace-ext-common-auth-authorization-oauth2-lib</name>
  <description>yospace-ext-common-auth-authorization-oauth2-lib</description>
  
  <dependencies>
<!--    api(project(":spi:common:core-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>  
<!--    api(project(":spi:common:auth-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-auth</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency> 
<!--    implementation(project(":spi:common:web-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-web</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>  
<!--    implementation(libs.jakarta.rsApi)
jakarta-rsApi = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "rsApi" }-->
      <dependency>
        <groupId>jakarta.ws.rs</groupId>
        <artifactId>jakarta.ws.rs-api</artifactId>
        <version>4.0.0</version>
      </dependency> 
<!--    implementation(libs.jakarta.annotation)
jakarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }-->
      <dependency>
        <groupId>jakarta.annotation</groupId>
        <artifactId>jakarta.annotation-api</artifactId>
        <version>3.0.0</version>
      </dependency> 
<!--    implementation(libs.nimbus.jwt)
nimbus-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbus" }-->
      <dependency>
        <groupId>com.nimbusds</groupId>
        <artifactId>nimbus-jose-jwt</artifactId>
        <version>10.9.1</version>
      </dependency> 

<!--    testImplementation(project(":core:common:junit"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>junit</artifactId>
        <version>0.18.0</version>
        <scope>test</scope>
      </dependency>
<!--    testRuntimeOnly(libs.jersey.common) // needs the RuntimeDelegate
jersey-common = { module = "org.glassfish.jersey.core:jersey-common", version.ref = "jersey" }  -->  
      <dependency>
        <groupId>org.glassfish.jersey.core</groupId>
        <artifactId>jersey-common</artifactId>
        <version>4.0.2</version>
        <scope>test</scope>
      </dependency>
 <!--      junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }-->
      <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-params</artifactId>
        <version>6.0.1</version>
        <scope>test</scope>
      </dependency>               
   </dependencies> 
</project>