<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.youdatax.web</groupId>
  <artifactId>youdatax-web-main-api</artifactId>
  <version>0.0.3-SNAPSHOT</version>
  <name>yospace-ext-common-api-core</name>
  <description>yospace-ext-common-api-core</description>
  
  <dependencies>
<!--    api(project(":spi:common:auth-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-auth</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    api(project(":spi:common:transform-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-transform</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":spi:common:web-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-web</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":spi:common:json-ld-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-json-ld</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    implementation(project(":core:common:lib:api-lib"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-lib-api</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    implementation(project(":core:common:lib:transform-lib"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-lib-transform</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    implementation(project(":core:common:lib:util-lib"))-->
      <dependency>
        <groupId>com.yospace.common</groupId>
        <artifactId>yospace-common-util-lib</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    implementation(project(":core:common:lib:validator-lib"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-lib-validator</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    implementation(libs.jakarta.rsApi)
jakarta-rsApi = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "rsApi" }-->
      <dependency>
        <groupId>jakarta.ws.rs</groupId>
        <artifactId>jakarta.ws.rs-api</artifactId>
        <version>4.0.0</version>
      </dependency>    
<!--    implementation(libs.swagger.annotations.jakarta)
swagger-annotations-jakarta = { module = "io.swagger.core.v3:swagger-annotations-jakarta", version.ref = "swagger" }-->
      <dependency>
        <groupId>io.swagger.core.v3</groupId>
        <artifactId>swagger-annotations-jakarta</artifactId>
        <version>2.2.40</version>
      </dependency>
      
<!--    testImplementation(libs.jersey.common)
jersey-common = { module = "org.glassfish.jersey.core:jersey-common", version.ref = "jersey" }-->
      <dependency>
        <groupId>org.glassfish.jersey.core</groupId>
        <artifactId>jersey-common</artifactId>
        <version>3.1.11</version>
        <scope>test</scope>
      </dependency>  
<!--    testImplementation(libs.jersey.server)
jersey-server = { module = "org.glassfish.jersey.core:jersey-server", version.ref = "jersey" }-->
      <dependency>
        <groupId>org.glassfish.jersey.core</groupId>
        <artifactId>jersey-server</artifactId>
        <version>3.1.11</version>
        <scope>test</scope>
      </dependency>
<!--    testImplementation(project(":core:common:junit"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>junit</artifactId>
        <version>0.18.0</version>
        <scope>test</scope>
      </dependency> 
<!--    testImplementation(project(":core:common:lib:query-lib"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>query-lib</artifactId>
        <version>0.18.0</version>
        <scope>test</scope>
      </dependency>
<!--    testImplementation(project(":core:common:lib:json-ld-lib"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>json-ld-lib</artifactId>
        <version>0.18.0</version>
        <scope>test</scope>
      </dependency>
   </dependencies> 
</project>