<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.youdatax.web</groupId>
  <artifactId>youdatax-web-authn-service-delegated</artifactId>
  <version>0.0.3.0</version>
  <name>yospace-ext-common-auth-delegated</name>
  <description>yospace-ext-common-auth-delegated</description>
  
  <dependencies>
<!--    api(project(":spi:common:auth-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-auth</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    api(project(":spi:common:token-spi"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>token-spi</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    implementation(project(":core:common:lib:crypto-common-lib"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-lib-crypto</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    implementation(project(":core:common:lib:token-lib"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-lib-token</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    implementation(libs.jakarta.rsApi)
jakarta-rsApi = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "rsApi" }-->
      <dependency>
        <groupId>jakarta.ws.rs</groupId>
        <artifactId>jakarta.ws.rs-api</artifactId>
        <version>4.0.0</version>
      </dependency>    
<!--    implementation(libs.nimbus.jwt)
nimbus-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbus" }-->
      <dependency>
        <groupId>com.nimbusds</groupId>
        <artifactId>nimbus-jose-jwt</artifactId>
        <version>10.6</version>
      </dependency>
      
<!--    testImplementation(project(":core:common:junit"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>junit</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    testImplementation(project(":core:common:lib:keys-lib"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>keys-lib</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    testImplementation(libs.wiremock)
wiremock = { module = "org.wiremock:wiremock-jetty12", version.ref = "wiremock" }-->
      <dependency>
        <groupId>org.wiremock</groupId>
        <artifactId>wiremock-jetty12</artifactId>
        <version>3.13.2</version>
      </dependency>    
<!--    testImplementation(libs.awaitility)
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }-->
      <dependency>
        <groupId>org.awaitility</groupId>
        <artifactId>awaitility</artifactId>
        <version>4.2.2</version>
      </dependency>
   </dependencies> 
</project>